### ISSUE TITLE
v3: Roadmap

### ISSUE THREAD

**Issue by mckn** [grafana/azure-data-explorer-datasource#110]
In version 3 of this plugin we will update the QueryEditor to include a visual query build as an alternative to the current text base query builder.

**Features:**

- [ ] Add new visual query editor.
- [ ] Add datasource configuration options for maximum number of records.
- [ ] Add datasource configuration options for default mode `text` or `visual`.
