### ISSUE TITLE
v3.1: Roadmap

### ISSUE THREAD

**Issue by mckn** [grafana/azure-data-explorer-datasource#113]
Things left to do before we should ship the `v3.1`.

**Bigger things:**
- [x] Add time over time functionality to the query editor. (timeshift) (#142)
- [x] Add the possibility to enable query caching (https://github.com/grafana/azure-data-explorer-datasource/issues/125).

**Smaller things:**
- [x] Autocomplete should populate some of the values prior to typing (selector in grafana/ui). (#145)
- [x] Add default view (raw or visual) to display when adding a new query. (https://github.com/grafana/azure-data-explorer-datasource/pull/132)
- [x] When searching/filtering in a column selector we should sort exact match on top (selector in grafana/ui). (#143, #148)
- [x] When doing the auto complete search we should include all other filter parameters to make sure we only display consistent values and also improves performance. (#141)
- [x] It is not possible to use "backspace" when removing a previous selected value in selector (selector in grafana/ui). (#147)
- [x] Where statement – we should add “has”, “!has” and “has_any”. (#129)
- [x] Where statement - ~in should have a multiselect as input type.
- [x] Introduce a "max number of returned values" setting for the datasource. Currently it is fixed to 10 000 which seems to be too low in some scenarios. 
- [x] Add Grafana eslint configuration and fix build warnings/errors. (https://github.com/grafana/azure-data-explorer-datasource/pull/134) 
- [x] Select menu should be wider to properly display option description (selector in grafana/ui). (#150)
