### ISSUE TITLE
Query performance improvements by enabling query caching

### ISSUE THREAD

**Issue by mckn** [grafana/azure-data-explorer-datasource#125]
To be able to increase the performance of making queries against ADX data sources with a massive amount of data we would like to add the possibility to enable query caching via the datasource settings.

The following things should be done:

- [x] When translating the time macros we should start using datetime operator in KQL. Also we should round the time values in the query to increase the chance of hitting the cache. Timestamp rounding should be configurable via the datasource settings. See example on implementation here: https://github.com/erik-jansen/azure-data-explorer-datasource/commit/b5817d64e24d37baaadbfadc73873931aaafc352 (#140)
- [x] We should make is possible to set the query cache max age for the queries via the datasource settings. See example on implementation here: https://github.com/erik-jansen/azure-data-explorer-datasource/commit/351c6f651957c1f440409307a71e1c5ef176b904  (#131)
- [x] There should also be a setting for toggling weak consistency when doing queries. See example on implementation here: https://github.com/erik-jansen/azure-data-explorer-datasource/commit/351c6f651957c1f440409307a71e1c5ef176b904  (#131)

More information about caching in ADX can be found here: https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/query-results-cache
