### ISSUE TITLE
v3.2: Roadmap

### ISSUE THREAD

**Issue by mckn** [grafana/azure-data-explorer-datasource#126]
Things left to do before we should ship the `v3.2`.

**Bigger things:**
- [x] Add support for handling Materialized Views. (#181)

**Smaller things:**
- [x] Change the Value columns/summarize to behave differently depending on if you create a time series or table query. (#178)
- [x] Changing global query limit to 0 will disable the limit. (#176)

**Comment by mckn** [comment]
https://github.com/grafana/azure-data-explorer-datasource/releases/tag/v3.2.0
