### ISSUE TITLE
User identity authentication in Azure Data Explorer

### ISSUE THREAD

**Issue by kostrse** [grafana/azure-data-explorer-datasource#534]
Work involved for support of user identity authentication in the Azure Data Explorer datasource.

Design discussion:
- https://github.com/grafana/grafana/discussions/62994

Based on:
- #366

### Experimental support
- [x] https://github.com/grafana/grafana-azure-sdk-go/pull/10
- [x] https://github.com/grafana/grafana-azure-sdk-go/pull/32
- [x] https://github.com/grafana/grafana/pull/50277
- [x] https://github.com/grafana/azure-data-explorer-datasource/pull/572
- [x] #381

### Feature release
- [ ] ???
